package com.example.floatkeys

import android.app.*
import android.content.*
import android.content.pm.ServiceInfo
import android.graphics.Color
import android.graphics.PixelFormat
import android.os.*
import android.view.*
import android.widget.*
import kotlin.math.abs

class OverlayService:Service(){
    private lateinit var wm:WindowManager; private lateinit var hub:TextView; private lateinit var hubParams:WindowManager.LayoutParams; private val keys=mutableListOf<Pair<TextView,WindowManager.LayoutParams>>(); private var closeButton:Pair<TextView,WindowManager.LayoutParams>?=null; private var expanded=true; private var hubX=0; private var hubY=0
    override fun onCreate(){super.onCreate();createNotification();wm=getSystemService(Context.WINDOW_SERVICE) as WindowManager;val s=resources.displayMetrics;hubX=s.widthPixels-Ui.dp(this,92);hubY=s.heightPixels-Ui.dp(this,180);addHub();setExpanded(true)}
    override fun onBind(intent:Intent?):IBinder?=null
    override fun onDestroy(){keys.forEach{(v,_)-> if(v.isPressed) v.isPressed=false};removeAll();super.onDestroy()}
    private fun createNotification(){val id="float_keys";if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel(id,"Float Keys",NotificationManager.IMPORTANCE_LOW));val stop=PendingIntent.getService(this,11,Intent(this,OverlayService::class.java).apply{action="STOP"},PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);val n=Notification.Builder(this,id).setSmallIcon(android.R.drawable.ic_menu_manage).setContentTitle("Float Keys is active").setContentText("Floating shortcut controls are on.").addAction(Notification.Action.Builder(null,"Stop",stop).build()).setOngoing(true).build();if(Build.VERSION.SDK_INT>=34)startForeground(73,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE) else startForeground(73,n)}
    override fun onStartCommand(intent:Intent?,flags:Int,startId:Int):Int{if(intent?.action=="STOP"){stopSelf();return START_NOT_STICKY};return START_STICKY}
    private fun baseParams(sizeDp:Int)=WindowManager.LayoutParams(Ui.dp(this,sizeDp),Ui.dp(this,sizeDp),WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL or WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM or WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT).apply{gravity=Gravity.TOP or Gravity.START}
    private fun roundButton(text:String,size:Int,color:Int)=TextView(this).apply{this.text=text;textSize=if(text.length<=2)17f else 12f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;background=Ui.circle(color);elevation=Ui.dp(this@OverlayService,6).toFloat()}
    private fun addHub(){hub=roundButton("⋮",64,Color.rgb(32,33,37));hubParams=baseParams(64).apply{x=hubX;y=hubY};wm.addView(hub,hubParams);var downX=0f;var downY=0f;var startX=0;var startY=0;var moved=false;hub.setOnTouchListener{_,e->when(e.actionMasked){MotionEvent.ACTION_DOWN->{downX=e.rawX;downY=e.rawY;startX=hubParams.x;startY=hubParams.y;moved=false;true};MotionEvent.ACTION_MOVE->{val dx=(e.rawX-downX).toInt();val dy=(e.rawY-downY).toInt();if(abs(dx)>5||abs(dy)>5)moved=true;hubParams.x=startX+dx;hubParams.y=startY+dy;hubX=hubParams.x;hubY=hubParams.y;wm.updateViewLayout(hub,hubParams);repositionArc();true};MotionEvent.ACTION_UP->{if(!moved)setExpanded(!expanded);true};else->false}}}
    private fun setExpanded(show:Boolean){expanded=show;if(show){if(keys.isEmpty()){repeat(4){slot->val s=ShortcutStore.get(this,slot);val v=roundButton(shortLabel(s),58,Color.rgb(62,106,225));val p=baseParams(58);v.setOnTouchListener{view,e->val cur=ShortcutStore.get(this,slot);when(cur.actionType){ActionType.TAP->{if(e.actionMasked==MotionEvent.ACTION_UP){if(!ShizukuBridge.send(cur))Toast.makeText(this,"Shortcut failed. Reconnect Shizuku.",Toast.LENGTH_SHORT).show();view.performClick()};true};ActionType.HOLD->{when(e.actionMasked){MotionEvent.ACTION_DOWN->{view.alpha=.62f;if(!ShizukuBridge.keyDown(cur.keyCode))Toast.makeText(this,"Modifier press failed. Reconnect Shizuku.",Toast.LENGTH_SHORT).show();true};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{ShizukuBridge.keyUp(cur.keyCode);view.alpha=1f;view.performClick();true};else->true}}}};wm.addView(v,p);keys+=v to p};val c=roundButton("×",42,Color.rgb(90,90,96));val cp=baseParams(42);c.setOnClickListener{stopSelf()};wm.addView(c,cp);closeButton=c to cp}else{keys.forEach{it.first.visibility=View.VISIBLE};closeButton?.first?.visibility=View.VISIBLE};repositionArc()}else{keys.forEach{it.first.visibility=View.GONE};closeButton?.first?.visibility=View.GONE}}
    private fun shortLabel(s:Shortcut):String{if(s.actionType==ActionType.HOLD)return KeyNames.displayName(s.keyCode);val mods=buildString{if(s.ctrl)append("⌃");if(s.shift)append("⇧");if(s.alt)append("⌥")};return mods+KeyNames.displayName(s.keyCode)}
    private fun repositionArc(){if(keys.isEmpty())return;val o=listOf(-82 to 10,-72 to -62,-18 to -102,52 to -72);keys.forEachIndexed{i,(v,p)->p.x=hubX+Ui.dp(this,o[i].first);p.y=hubY+Ui.dp(this,o[i].second);try{wm.updateViewLayout(v,p)}catch(_:Throwable){}};closeButton?.let{(v,p)->p.x=hubX+Ui.dp(this,68);p.y=hubY+Ui.dp(this,8);try{wm.updateViewLayout(v,p)}catch(_:Throwable){}}}
    private fun removeAll(){try{wm.removeView(hub)}catch(_:Throwable){};keys.forEach{(v,_)->try{wm.removeView(v)}catch(_:Throwable){}};closeButton?.let{(v,_)->try{wm.removeView(v)}catch(_:Throwable){}};keys.clear();closeButton=null}
}
